[project]
authors = ["cgeady <caryn@geady.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MIRV"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
numpy = ">=2.2.2,<3"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.0,<4"
lifelines = ">=0.30.0,<0.31"
scikit-learn = ">=1.6.1,<2"
scipy = ">=1.15.1,<2"
pip = ">=25.0.1,<26"
ipykernel = ">=6.29.5,<7"
statannotations = ">=0.7.1,<0.8"
jinja2 = ">=3.1.5,<4"


