[project]
authors = ["cgeady <caryn@geady.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "MIRV"
platforms = ["osx-arm64","linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.0,<4"
lifelines = ">=0.30.0,<0.31"
statannotations = ">=0.7.1,<0.8"
jinja2 = ">=3.1.5,<4"

[pypi-dependencies]
torch = ">=2.6.0, <3"
torch_geometric = "*"
torch-geometric = ">=2.6.1, <3"
