[project]
authors = ["caryn-geady <caryn@geady.com>"]
channels = ["conda-forge"]
description = "Investigating the relationship between Measured Intra-patient Radiomic Variability (MIRV) and treatment response in the metastatic setting."
name = "MIRV"
platforms = ["osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
mirvpipe = 'python workflow/scripts/mirvpipe.py'

[dependencies]
pandas = ">=2.2.3,<3"
numpy = ">=2.1.3,<3"
scikit-learn = ">=1.5.2,<2"
scipy = ">=1.14.1,<2"
matplotlib = ">=3.9.2,<4"
seaborn = ">=0.13.2,<0.14"
statannot = ">=0.2.3,<0.3"
statsmodels = ">=0.14.4,<0.15"
networkx = ">=3.4.2,<4"
pip = ">=24.3.1,<25"
ipykernel = ">=6.29.5,<7"
lifelines = ">=0.30.0,<0.31"
statannotations = ">=0.7.1,<0.8"
upsetplot = ">=0.9.0,<0.10"
jinja2 = ">=3.1.6,<4"
qrcode = ">=8.0,<9"
